@startuml

        <style>
          .described {
            BackGroundColor white
            FontColor black
          }
          .checklist {
            FontColor black
          }
          .burn {
            BackgroundColor #FF2E00
          }
          .hot {
            BackgroundColor #FFC0B2
          }
          .blocked {
            BackgroundColor #FF7452
          }
          .inprogress {
            BackgroundColor #FFC400
          }
          .intest {
            BackgroundColor #66BAFF
          }
          .done {
            BackgroundColor #36B37E
          }
          .closed {
            BackgroundColor #006644
          }

        </style>
        skinparam state {
          BackgroundColor #FAFBFC
          BackgroundColor<<todo>> #EBECF0

          BackgroundColor<<burn>> #FF2E00
          BackgroundColor<<hot>> #FFC0B2

          BackgroundColor<<blocked>> #FF7452
          BackgroundColor<<inprogress>> #FFC400
          BackgroundColor<<intest>> #66BAFF
          BackgroundColor<<done>> #36B37E
          BackgroundColor<<closed>> #006644
          BorderColor #091E42
          BorderColor<<p0>> #BF2600
          BorderColor<<p1>> #BF2600
          BorderColor<<p2>> #091E42
          BorderColor<<p3>> #C1C7D0
          BorderColor<<p4>> #FFFFFF
          FontColor<<p0>> #BF2600
          FontColor<<p1>> #BF2600
          FontColor<<p2>> #091E42
          FontColor<<p3>> #C1C7D0
          FontColor<<p4>> #FFFFFF
          HyperLinkColor<<CARD_TYPE_2-1>> #403294
HyperLinkColor<<CARD_TYPE_2-2>> #0747A6
HyperLinkColor<<CARD_TYPE_2-3>> #008DA6
HyperLinkColor<<BUG>> #BF2600
HyperLinkColor<<CARD_TYPE_2-4>> #00a61c
HyperLinkColor<<CARD_TYPE_2-5>> #a58300

          ArrowColor #091E42
        }

state "[[https://trello.com/c/K9BgcLep Unreal Engine]]" as card542  <<todo>> <<CARD_TYPE_2-1>> <<p2>> {

  state "[[https://trello.com/c/wMjEcGmX Тайлмап]]" as card543  <<todo>> <<CARD_TYPE_2-2>> <<p2>> {

    state "[[https://trello.com/c/O0JwTetZ Анимированные тайлы]]" as card544  <<done>> <<CARD_TYPE_2-3>> <<p2>> {

      state "[[https://trello.com/c/1QZeGiry Сделать замену\nтайлов\nанимированными\nтайлами]]" as card546  <<done>> <<CARD_TYPE_2-4>> <<p2>> {
       }
      card546 : TASK - P2
      card546 : DONE
    }
    card544 : PART - P2
    card544 : DONE

    state "[[https://trello.com/c/zHT6Nj1y Параллакс]]" as card545  <<done>> <<CARD_TYPE_2-3>> <<p2>> {

      state "[[https://trello.com/c/OfleV32G Сделать параллакс\nдля определенный\nтайлмапы]]" as card547  <<done>> <<CARD_TYPE_2-4>> <<p2>> {
       }
      card547 : TASK - P2
      card547 : DONE
    }
    card545 : PART - P2
    card545 : DONE
  }
  card543 : FEATURE - P2
  card543 : TODO
}
card542 : EPIC - P2
card542 : TODO

state "[[https://trello.com/c/M8bydkon Сущности]]" as card449 <<hot>> <<todo>> <<CARD_TYPE_2-1>> <<p1>> {
 json Described_card449 <<described>> {
  "To Create": [
    {
      "Абстрактный персонаж": [
        {
          "Неподвижная болванка персонажа": [
            "Сделать класс для персонажа",
            "Сделать возможность добавлять анимации через PaperZD",
            "Спавнить персонажа на уровне по спавн-поинту на тайлмапе",
            "Сделать чтобы не проваливался в землю"
          ]
        },
        {
          "Идл | Абстрактный": [
            "Сделать запуск идл анимации"
          ]
        },
        {
          "Ходьба | Абстрактный": [
            "Сделать триггер для передвижения персонажа",
            "Сделать запуск анимации ходьбы"
          ]
        },
        {
          "Прыжок | Абстрактный": [
            "Сделать триггер для прыжка",
            "Сделать запуск анимации прыжка",
            "Сделать запуск анимации падения",
            "Ограничить прыжок одним разом"
          ]
        },
        {
          "Подъем предметов | Абстрактный": [
            "Сделать триггер для подъема ближайшего предмета",
            "Запустить анимацию ходьбы с поднятым предметом"
          ]
        },
        {
          "Толкание предметов | Абстрактный": [
            "Сделать толкание предметов",
            "Запустить анимацию толкания предмета"
          ]
        },
        {
          "Смерть | Абстрактный": [
            "Сделать уничтожение объекта",
            "Запустить анимацию смерти",
            "Запустить частицы"
          ]
        },
        {
          "Применение способности | Абстрактный": [
            "Сделать триггер применения способности",
            "Запустить частицы применения способности"
          ]
        }
      ]
    }
  ]
}
}
card449 : EPIC - P1
card449 : TODO

state "[[https://trello.com/c/OB3PXE2L Персонажи]]" as card442 <<hot>> <<todo>> <<CARD_TYPE_2-1>> <<p1>> {
 json Described_card442 <<described>> {
  "To Create": [
    {
      "Управляемый персонаж": [
        {
          "Управление персонажем": [
            "Запустить триггер ходьбы управлением",
            "Запустить триггер прыжка управлением",
            "Запустить триггер подъема предмета",
            "Запустить триггер применения способности"
          ]
        }
      ]
    },
    {
      "Персонаж Far Away": [
        {
          "Базовые анимации Far Away": [
            "Анимация ходьбы Far Away",
            "Анимация Прыжка Far Away"
          ]
        },
        {
          "Дополнительные анимации Far Away": [
            "Идл Анимация Far Away",
            "Анимация Падения Far Away",
            "Анимация Ходьбы с предметом Far Away",
            "Анимация Толкания предмета Far Away"
          ]
        }
      ]
    },
    {
      "Персонаж Long Ago": [
        {
          "Базовые анимации Long Ago": [
            "Анимация ходьбы Long Ago",
            "Анимация Прыжка Long Ago"
          ]
        },
        {
          "Дополнительные анимации Long Ago": [
            "Идл Анимация Long Ago",
            "Анимация Падения Long Ago",
            "Анимация Ходьбы с предметом Long Ago",
            "Анимация Толкания предмета Long Ago"
          ]
        }
      ]
    }
  ]
}
}
card442 : EPIC - P1
card442 : TODO

state "[[https://trello.com/c/kmnl1upe \nПредметы/Мобы/Механика]]" as card448 <<hot>> <<todo>> <<CARD_TYPE_2-1>> <<p1>> {
 json Described_card448 <<described>> {
  "To Create": [
    {
      "Портал": [
        {
          "Общее Портал": [
            "Сделать объект портала",
            "Изображение выключенного портала",
            "Изображение активного портала",
            "Частицы активного портала",
            "Частицы входа и выхода портала, когда в него кто-то заходит",
            "Сделать триггер включения/выключения портала"
          ]
        },
        {
          "Прямой портал": [
            "Сделать бесшовную телепортацию для прямого портала",
            "Пофикстать проблему колижн боксом при телепортации"
          ]
        },
        {
          "Обратный портал": [
            "Сделать бесшовную телепортацию для обратного портала",
            "Решить проблему инвертирования управления",
            "Сделать фикс для инвертирования управления",
            "Изображение обратного портала. Чтобы отличать от прямого. OPTIONAL"
          ]
        },
        {
          "Горизонтальный портал": [
            "Сделать бесшовную телепортацию для горизонтального портала"
          ]
        },
        {
          "Портал под углом": [
            "Сделать бесшовную телепортацию для портала под углом"
          ]
        },
        {
          "Портал на подвижной платформе": [
            "Проверить что все работает на подвижных платформах"
          ]
        },
        "Установка портала игроком",
        "Жидкость через портал"
      ]
    },
    {
      "Перемещение обменом с предметом": [
        "Продумать как будет работать"
      ]
    },
    {
      "Пушка": [
        {
          "Общее Пушка": [
            "Сделать объект для пушки",
            "Нарисовать пушку",
            "Частицы выстрела пушки"
          ]
        },
        {
          "Пушка стреляет под заданным углом": [
            "Сделать чтобы пушка стреляла под заданным углом"
          ]
        }
      ]
    },
    {
      "Снаряд": [
        {
          "Общее Снаряд": [
            "Сделать объект для снаряда",
            "Нарисовать снаряд",
            "Сделать чтобы пуля создавалась из пула объектов",
            "Сделать чтобы пуля летела в заданном направлении, с заданной скоростью",
            "Сделать чтобы снаряд ранил игрока",
            "Сделать чтобы снаряд ранил мобов",
            "Сделать чтобы снаряд ранил только если летит прямо в сущность",
            "Проверить что на снаряд можно прыгнуть в остановленном времени",
            "Частицы разбивания снаряда"
          ]
        },
        {
          "Обычный снаряд - разбивается сразу": [
            "Сделать чтобы пуля разбивалась при столкновении"
          ]
        },
        {
          "Снаряд рикошет": [
            "Сделать чтобы пуля рикошетила"
          ]
        }
      ]
    },
    {
      "Ящик": [
        {
          "Общее Ящик": [
            "Сделать объект для ящика",
            "Нарисовать ящик"
          ]
        },
        {
          "Толкание предметов": [
            "Сделать возможность толкать предметы"
          ]
        }
      ]
    },
    {
      "Патрулирующий моб": [
        {
          "Общее Патрулирующий моб": [
            "Сделать объект для моба",
            "Сделать чтобы моб патрулировал от стенки до стенки",
            "Сделать чтобы моб ранил игрока",
            "Нарисовать тестового моба"
          ]
        },
        {
          "Прыжок на моба": [
            "Сделать чтобы моб погибал если прыгнуть сверху",
            "Сделать отскок игрока от моба в зависимости от высоты прыжка"
          ]
        }
      ]
    },
    {
      "Собираемый предмет": [
        {
          "Общее Собираемый предмет": [
            "Сделать объект собираемого предмета"
          ]
        },
        {
          "Механика Собираемый предмет": [
            "Сделать счетчик собранных предметов"
          ]
        }
      ]
    },
    {
      "Поднимаемый предмет": [
        {
          "Поднятие предметов (ящики/пушки)": [
            "Сделать возможность поднимать предметы",
            "Сделать возможность бросать предметы"
          ]
        }
      ]
    },
    {
      "Подвижные платформы": [
        {
          "Общее платформы": [
            "Сделать объект для платформы"
          ]
        },
        {
          "Механика платформы": [
            "Сделать движение платформы по маршруту",
            "Сделать движение платформы в одну сторону (по рычагу)",
            "Сделать исчезающую при касании платформу"
          ]
        }
      ]
    },
    {
      "Дверь": [
        {
          "Общее Дверь": [
            "Сделать объект для двери",
            "Нарисовать дверь",
            "Сделать чтобы дверь не пускала в закрытом виде"
          ]
        }
      ]
    },
    {
      "Ключ": [
        {
          "Общее Ключ": [
            "Сделать объект для ключа",
            "Нарисовать ключ",
            "Сделать чтобы ключ подбирался игроком",
            "Сделать чтобы дверь открывалась при касании ключом"
          ]
        }
      ]
    },
    {
      "Рычаг": [
        {
          "Общее Рычаг": [
            "Сделать объект для рычага",
            "Нарисовать рычаг"
          ]
        },
        {
          "Механика Рычаг": [
            "Сделать чтобы игрок мог использовать рычаг",
            "Сделать чтобы снаряд переводил рычаг в положение по направлению полета",
            "Сделать чтобы рычаг открывал/закрывал дверь",
            "Сделать чтобы рычаг запускал/отключал платформу",
            "Сделать чтобы рычаг запускал/отключал пушку"
          ]
        }
      ]
    },
    "Остановка времени",
    "Переключение измерений"
  ]
}
}
card448 : EPIC - P1
card448 : TODO

state "[[https://trello.com/c/thSPma3j Головоломки]]" as card95 <<hot>> <<todo>> <<CARD_TYPE_2-1>> <<p1>> {
 json Described_card95 <<described>> {
  "To Create": [
    {
      "Обычные Головоломки": [
        "Придумать головоломки  | Обычные"
      ]
    },
    {
      "Головоломки с порталами": [
        "Придумать головоломки  | Порталы"
      ]
    },
    {
      "Головоломки со временем": [
        "Придумать головоломки  | Время"
      ]
    },
    {
      "Головоломки с порталами и со временем": [
        "Придумать головоломки  | Порталы и Время"
      ]
    }
  ]
}
}
card95 : EPIC - P1
card95 : TODO

state "[[https://trello.com/c/5RnEewpx Локации]]" as card93  <<todo>> <<CARD_TYPE_2-1>> <<p2>> {
 json Described_card93 <<described>> {
  "To Create": [
    {
      "Деревня": [
        {
          "Тайлсет деревни": [
            "Нарисовать тайлсет",
            "Нарисовать анимированные мелочи",
            "Загрузить тайлсет в Tiled"
          ]
        },
        {
          "Фоновая музыка": [
            "Сочинить музыку",
            "Добавить музыку для локации"
          ]
        },
        {
          "Местный моб": [
            "Придумать моба для локации",
            "Сделать энтити",
            "Анимация ходьбы",
            "Анимация смерти",
            "Идл звук моба",
            "Звук смерти моба",
            "Частицы смерти моба"
          ]
        },
        {
          "Местный подбираемый предмет": [
            "Придумать Предмет для локации",
            "Сделать энтити",
            "Нарисовать предмет",
            "Звук подбора предмета",
            "Сделать катсцену как персанаж приносит добычу"
          ]
        }
      ]
    },
    {
      "Деревня в огне": [
        {
          "Тайлсет": [
            "Нарисовать концепт",
            "Нарисовать тайлсет",
            "Нарисовать анимированные мелочи",
            "Загрузить тайлсет в Tiled"
          ]
        },
        {
          "Фоновая музыка": [
            "Сочинить музыку",
            "Добавить музыку для локации"
          ]
        },
        {
          "Местный моб": [
            "Придумать моба для локации",
            "Сделать энтити",
            "Анимация ходьбы",
            "Анимация смерти",
            "Идл звук моба",
            "Звук смерти моба",
            "Частицы смерти моба"
          ]
        },
        {
          "Местный подбираемый предмет": [
            "Придумать Предмет для локации",
            "Сделать энтити",
            "Нарисовать предмет",
            "Звук подбора предмета",
            "Сделать катсцену как персанаж приносит добычу"
          ]
        }
      ]
    },
    {
      "Лес": [
        {
          "Тайлсет": [
            "Нарисовать концепт",
            "Нарисовать тайлсет",
            "Нарисовать анимированные мелочи",
            "Загрузить тайлсет в Tiled"
          ]
        },
        {
          "Фоновая музыка": [
            "Сочинить музыку",
            "Добавить музыку для локации"
          ]
        },
        {
          "Местный моб": [
            "Придумать моба для локации",
            "Сделать энтити",
            "Анимация ходьбы",
            "Анимация смерти",
            "Идл звук моба",
            "Звук смерти моба",
            "Частицы смерти моба"
          ]
        },
        {
          "Местный подбираемый предмет": [
            "Придумать Предмет для локации",
            "Сделать энтити",
            "Нарисовать предмет",
            "Звук подбора предмета",
            "Сделать катсцену как персанаж приносит добычу"
          ]
        }
      ]
    },
    {
      "Каменная степь": [
        {
          "Тайлсет": [
            "Нарисовать концепт",
            "Нарисовать тайлсет",
            "Нарисовать анимированные мелочи",
            "Загрузить тайлсет в Tiled"
          ]
        },
        {
          "Фоновая музыка": [
            "Сочинить музыку",
            "Добавить музыку для локации"
          ]
        },
        {
          "Местный моб": [
            "Придумать моба для локации",
            "Сделать энтити",
            "Анимация ходьбы",
            "Анимация смерти",
            "Идл звук моба",
            "Звук смерти моба",
            "Частицы смерти моба"
          ]
        },
        {
          "Местный подбираемый предмет": [
            "Придумать Предмет для локации",
            "Сделать энтити",
            "Нарисовать предмет",
            "Звук подбора предмета",
            "Сделать катсцену как персанаж приносит добычу"
          ]
        }
      ]
    },
    {
      "Море": [
        {
          "Тайлсет": [
            "Нарисовать концепт",
            "Нарисовать тайлсет",
            "Нарисовать анимированные мелочи",
            "Загрузить тайлсет в Tiled"
          ]
        },
        {
          "Фоновая музыка": [
            "Сочинить музыку",
            "Добавить музыку для локации"
          ]
        },
        {
          "Местный моб": [
            "Придумать моба для локации",
            "Сделать энтити",
            "Анимация ходьбы",
            "Анимация смерти",
            "Идл звук моба",
            "Звук смерти моба",
            "Частицы смерти моба"
          ]
        },
        {
          "Местный подбираемый предмет": [
            "Придумать Предмет для локации",
            "Сделать энтити",
            "Нарисовать предмет",
            "Звук подбора предмета",
            "Сделать катсцену как персанаж приносит добычу"
          ]
        }
      ]
    },
    {
      "Пустыня": [
        {
          "Тайлсет": [
            "Нарисовать концепт",
            "Нарисовать тайлсет",
            "Нарисовать анимированные мелочи",
            "Загрузить тайлсет в Tiled"
          ]
        },
        {
          "Фоновая музыка": [
            "Сочинить музыку",
            "Добавить музыку для локации"
          ]
        },
        {
          "Местный моб": [
            "Придумать моба для локации",
            "Сделать энтити",
            "Анимация ходьбы",
            "Анимация смерти",
            "Идл звук моба",
            "Звук смерти моба",
            "Частицы смерти моба"
          ]
        },
        {
          "Местный подбираемый предмет": [
            "Придумать Предмет для локации",
            "Сделать энтити",
            "Нарисовать предмет",
            "Звук подбора предмета",
            "Сделать катсцену как персанаж приносит добычу"
          ]
        }
      ]
    },
    {
      "Горы": [
        {
          "Тайлсет": [
            "Нарисовать концепт",
            "Нарисовать тайлсет",
            "Нарисовать анимированные мелочи",
            "Загрузить тайлсет в Tiled"
          ]
        },
        {
          "Фоновая музыка": [
            "Сочинить музыку",
            "Добавить музыку для локации"
          ]
        },
        {
          "Местный моб": [
            "Придумать моба для локации",
            "Сделать энтити",
            "Анимация ходьбы",
            "Анимация смерти",
            "Идл звук моба",
            "Звук смерти моба",
            "Частицы смерти моба"
          ]
        },
        {
          "Местный подбираемый предмет": [
            "Придумать Предмет для локации",
            "Сделать энтити",
            "Нарисовать предмет",
            "Звук подбора предмета",
            "Сделать катсцену как персанаж приносит добычу"
          ]
        }
      ]
    },
    {
      "Пещера": [
        {
          "Тайлсет": [
            "Нарисовать концепт",
            "Нарисовать тайлсет",
            "Нарисовать анимированные мелочи",
            "Загрузить тайлсет в Tiled"
          ]
        },
        {
          "Фоновая музыка": [
            "Сочинить музыку",
            "Добавить музыку для локации"
          ]
        },
        {
          "Местный моб": [
            "Придумать моба для локации",
            "Сделать энтити",
            "Анимация ходьбы",
            "Анимация смерти",
            "Идл звук моба",
            "Звук смерти моба",
            "Частицы смерти моба"
          ]
        },
        {
          "Местный подбираемый предмет": [
            "Придумать Предмет для локации",
            "Сделать энтити",
            "Нарисовать предмет",
            "Звук подбора предмета",
            "Сделать катсцену как персанаж приносит добычу"
          ]
        }
      ]
    },
    {
      "Вулкан": [
        {
          "Тайлсет": [
            "Нарисовать концепт",
            "Нарисовать тайлсет",
            "Нарисовать анимированные мелочи",
            "Загрузить тайлсет в Tiled"
          ]
        },
        {
          "Фоновая музыка": [
            "Сочинить музыку",
            "Добавить музыку для локации"
          ]
        },
        {
          "Местный моб": [
            "Придумать моба для локации",
            "Сделать энтити",
            "Анимация ходьбы",
            "Анимация смерти",
            "Идл звук моба",
            "Звук смерти моба",
            "Частицы смерти моба"
          ]
        },
        {
          "Местный подбираемый предмет": [
            "Придумать Предмет для локации",
            "Сделать энтити",
            "Нарисовать предмет",
            "Звук подбора предмета",
            "Сделать катсцену как персанаж приносит добычу"
          ]
        }
      ]
    }
  ]
}

  state "[[https://trello.com/c/3UuKlJdp Деревня]]" as card501  <<todo>> <<CARD_TYPE_2-2>> <<p2>> {

    state "[[https://trello.com/c/GVQraAKf Тайлсет деревни]]" as card502  <<todo>> <<CARD_TYPE_2-3>> <<p2>> {

      state "[[https://trello.com/c/2cultoZp Нарисовать концепт\nдеревни]]" as card503  <<done>> <<CARD_TYPE_2-4>> <<p2>> {
       }
      card503 : TASK - P2
      card503 : DONE
    }
    card502 : PART - P2
    card502 : TODO
  }
  card501 : FEATURE - P2
  card501 : TODO
}
card93 : EPIC - P2
card93 : TODO

state "[[https://trello.com/c/N0VExjfO Неписи с диалогами]]" as card96  <<todo>> <<CARD_TYPE_2-1>> <<p3>> {
 json Described_card96 <<described>> {
  "To Create": [
    "TBD"
  ]
}
}
card96 : EPIC - P3
card96 : TODO

state "[[https://trello.com/c/GvaRpKQJ Менюшки]]" as card97  <<todo>> <<CARD_TYPE_2-1>> <<p3>> {
 json Described_card97 <<described>> {
  "To Create": [
    {
      "Главное меню": [
        {
          "Кнопка Играть": [
            "Переход на экран выбора персонажа",
            "Нарисовать кнопку Играть"
          ]
        },
        {
          "Кнопка Настройки": [
            "Переход на меню настроек",
            "Нарисовать кнопку Настройки"
          ]
        },
        {
          "Кнопка Авторы": [
            "Переход на экран с текстом",
            "Нарисовать кнопку Авторы"
          ]
        },
        {
          "Кнопка Выход": [
            "Сделать выход из игры",
            "Нарисовать кнопку Выход"
          ]
        },
        {
          "Разметка экрана": [
            "Сверстать кнопки"
          ]
        }
      ]
    },
    {
      "Меню Настройки": [
        {
          "Звук ВКЛ/ВЫКЛ": [
            "Сделать переключение звука",
            "Иконки для звука ВКЛ/ВЫКЛ",
            "Сделать тоггл компонент"
          ]
        },
        {
          "Фулскрин ВКЛ/ВЫКЛ": [
            "Сделать переключение фулскрина",
            "Иконки для фулскрина ВКЛ/ВЫКЛ",
            "Сделать тоггл компонент"
          ]
        },
        {
          "Управление": [
            "Сделать компонент для переключения управления",
            "Сделать тачскрин управление",
            "Сделать управление на клаве",
            "Сделать переключение между ними",
            "Иконка для управления",
            "Иконка для тачскрина",
            "Иконка для клавы"
          ]
        },
        {
          "Кнопка Назад": [
            "Переход на главное меню"
          ]
        },
        {
          "Разметка экрана": [
            "Сверстать меню настроек"
          ]
        }
      ]
    },
    {
      "Меню Авторы": [
        {
          "Компонент с текстом": [
            "Сделать компонент для текста",
            "Бокс для текста, шрифт или иконки"
          ]
        },
        {
          "Кнопка Назад": [
            "Переход на главное меню"
          ]
        }
      ]
    },
    {
      "Меню Выбор персонажа/карта уровней": [
        {
          "Компоненты": [
            "Сделать компонент со списком персонажей",
            "Придумать какие будут локации, сделать концепт карты уровней",
            "Список с персонажами",
            "Карта локаций с дорожками между уровней.",
            "Кнопка выбора уровня",
            "Анимация персонажа над текущим уровнем"
          ]
        },
        {
          "Разметка экрана": [
            "Сверстать экран выбора персонажа",
            "Сверстать кнопки с уровнями на карте уровней"
          ]
        },
        {
          "Кнопка Назад": [
            "Переход на главное меню"
          ]
        },
        {
          "Кнопка выбора уровня": [
            "Сделать старт определенного уровня со звуком",
            "Звук начала игры"
          ]
        }
      ]
    },
    {
      "Меню. Общее": [
        {
          "Ядро": [
            "Сделать отдельный мод для всего меню",
            "Сделать переходы между экранами туда и обратно",
            "Фоновая музыка для всего меню",
            "Запустить музыку одну на все"
          ]
        },
        {
          "Компонент Экрана": [
            "Сделать компонент для экрана с фоном",
            "Сделать возможность добавлять другие компоненты"
          ]
        },
        {
          "Компонент кнопка с иконкой": [
            "Сделать кнопку с иконкой",
            "Иконка для кнопки Назад",
            "Звук нажатия на кнопку"
          ]
        }
      ]
    },
    {
      "Меню паузы": [
        {
          "Разметка": [
            "Остановить игру",
            "Сверстать окно паузы",
            "Окошко паузы"
          ]
        },
        {
          "Кнопка Продолжить": [
            "Вернуть к игре",
            "кнопка Продолжить"
          ]
        },
        {
          "Кнопка Настройки": [
            "Открыть экран с настройками из главного меню"
          ]
        },
        {
          "Кнопка Главное меню": [
            "Переключить на главное меню",
            "кнопка Главное меню"
          ]
        }
      ]
    }
  ]
}
}
card97 : EPIC - P3
card97 : TODO

state "[[https://trello.com/c/7ZQSXg5t Заставки]]" as card94  <<todo>> <<CARD_TYPE_2-1>> <<p4>> {
 json Described_card94 <<described>> {
  "To Create": [
    {
      "Общее": [
        {
          "Режим заставки": [
            "Сделать режим показа заставки",
            "Сделать перемещение энтитей по сценарию",
            "Сделать триггер начала заставки",
            "Сделать возвращение к игре"
          ]
        }
      ]
    },
    {
      "Предыстории": [
        "Far Away",
        "Long Ago"
      ]
    },
    "Начало катастрофы",
    "Концовка"
  ]
}
}
card94 : EPIC - P4
card94 : TODO

state "[[https://trello.com/c/cte6TUFC Собрать ассеты]]" as card452  <<inprogress>> <<CARD_TYPE_2-4>> <<p1>> {
 json " " as Checklists_card452 <<checklist>>  <<inprogress>> {
  "Чек-лист": [
    "Звуковые эффекты",
    "Уровни",
    "Визуальные эффекты",
    "Модели окружения",
    "Модели персонажей",
    "UI элементы"
  ]
}
}
card452 : TASK - P1
card452 : IN PROGRESS

state "[[https://trello.com/c/GlB83x1h Перелопатить трелло\nдоску]]" as card88 <<closed>> {
 }
card88 : CLOSED

state "[[https://trello.com/c/7WTpZZp1 Дать\nпредварительный\nфидбэк]]" as card447 <<closed>> {
 }
card447 : CLOSED

state "[[https://trello.com/c/AGi5GzJC Описать идею]]" as card7 <<closed>> {
 }
card7 : CLOSED
card449 --> card442
card449 --> card448
card449 --> card96
card448 --> card95
card93 --> card96
card96 --> card94







        @enduml